import type { StatPacket } from '@/lib/compute/types';

/**
 * Delivery formatting.
 *
 * Formatted *for* the destination, not one blob reformatted four times. Sleeper
 * league chat is plain text on a tight character budget; email is HTML; Discord
 * and Slack take structured blocks. Each target below takes the same verified
 * report body and renders it natively.
 *
 * Every target carries the footer. The report is the growth loop: one
 * commissioner installs it and eleven people read their own name in it, so the
 * footer is the acquisition channel and it is not optional.
 */

export const FOOTER_TEXT = 'Generated by LeagueOps — leagueops.app';
export const FOOTER_URL = 'https://leagueops.app';

export type DeliveryTarget = 'sleeper' | 'email' | 'discord' | 'slack' | 'plain';

/** Sleeper's chat box truncates hard, so the recap is split, not clipped. */
export const SLEEPER_CHAR_BUDGET = 1800;

export type Section = { heading: string; body: string };

/** Split a markdown report into its sections, in document order. */
export function parseSections(markdown: string): Section[] {
  const lines = markdown.split('\n');
  const sections: Section[] = [];
  let current: Section | null = null;

  for (const line of lines) {
    const heading = /^#{1,6}\s+(.*)$/.exec(line.trim());
    if (heading) {
      if (current) sections.push(current);
      current = { heading: (heading[1] as string).trim(), body: '' };
      continue;
    }
    if (!current) current = { heading: '', body: '' };
    current.body += `${line}\n`;
  }

  if (current) sections.push(current);
  return sections.map((s) => ({ ...s, body: s.body.trim() }));
}

/**
 * Sleeper league chat: plain text, no markdown, split into messages that fit the
 * budget. Splits fall on section boundaries where possible and on paragraph
 * boundaries otherwise — never mid-sentence.
 */
export function formatForSleeper(markdown: string, budget = SLEEPER_CHAR_BUDGET): string[] {
  const sections = parseSections(markdown);
  const blocks = sections.map((section) => {
    const heading = section.heading ? `${section.heading.toUpperCase()}\n` : '';
    return `${heading}${stripMarkdown(section.body)}`.trim();
  });

  const messages: string[] = [];
  let buffer = '';

  const flush = () => {
    if (buffer.trim()) messages.push(buffer.trim());
    buffer = '';
  };

  for (const block of blocks) {
    if (block === '') continue;
    for (const piece of splitToBudget(block, budget)) {
      if (buffer.length + piece.length + 2 > budget) flush();
      buffer += (buffer ? '\n\n' : '') + piece;
    }
  }
  flush();

  if (messages.length === 0) return [FOOTER_TEXT];

  const last = messages[messages.length - 1] as string;
  const withFooter = `${last}\n\n${FOOTER_TEXT}`;
  if (withFooter.length <= budget) messages[messages.length - 1] = withFooter;
  else messages.push(FOOTER_TEXT);

  return messages;
}

/** Break one oversized block on paragraph, then sentence, boundaries. */
function splitToBudget(block: string, budget: number): string[] {
  if (block.length <= budget) return [block];

  const out: string[] = [];
  let buffer = '';

  const units = block.split(/\n\n+/).flatMap((paragraph) =>
    paragraph.length <= budget ? [paragraph] : paragraph.split(/(?<=[.!?])\s+/),
  );

  for (const unit of units) {
    // A single sentence longer than the budget is truncated; nothing else can
    // be done without cutting mid-word in a way readers would notice more.
    const piece = unit.length > budget ? `${unit.slice(0, budget - 1)}…` : unit;
    if (buffer.length + piece.length + 2 > budget) {
      if (buffer) out.push(buffer.trim());
      buffer = piece;
    } else {
      buffer += (buffer ? '\n\n' : '') + piece;
    }
  }
  if (buffer.trim()) out.push(buffer.trim());
  return out;
}

export function stripMarkdown(text: string): string {
  return text
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/(?<!\*)\*([^*\n]+)\*(?!\*)/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    // [ \t] rather than \s: \s crosses newlines, so a greedy match would start
    // on the blank line above a bullet and swallow the paragraph break.
    .replace(/^[ \t]*[-*+][ \t]+/gm, '• ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export function formatForEmail(markdown: string, packet: StatPacket): string {
  const sections = parseSections(markdown);
  const body = sections
    .map((section) => {
      const heading = section.heading
        ? `<h2 style="margin:28px 0 10px;font:600 17px/1.3 system-ui,-apple-system,sans-serif;color:#111">${escapeHtml(section.heading)}</h2>`
        : '';
      return heading + renderParagraphs(section.body);
    })
    .join('\n');

  return `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(packet.leagueName)} — Week ${packet.week}</title></head>
<body style="margin:0;background:#f6f6f4;padding:24px 12px">
<div style="max-width:640px;margin:0 auto;background:#fff;border-radius:10px;padding:28px 24px;font:15px/1.6 system-ui,-apple-system,sans-serif;color:#222">
<div style="font:600 13px/1 system-ui,sans-serif;letter-spacing:.08em;text-transform:uppercase;color:#888">
${escapeHtml(packet.leagueName)} · Week ${packet.week}</div>
<h1 style="margin:8px 0 20px;font:700 24px/1.2 system-ui,sans-serif;color:#111">The Commissioner's Report</h1>
${body}
<hr style="border:0;border-top:1px solid #e7e7e4;margin:28px 0 14px">
<p style="margin:0;font:13px/1.5 system-ui,sans-serif;color:#888">
<a href="${FOOTER_URL}" style="color:#888">${escapeHtml(FOOTER_TEXT)}</a></p>
</div></body></html>`;
}

function renderParagraphs(body: string): string {
  return body
    .split(/\n\n+/)
    .filter((p) => p.trim())
    .map((paragraph) => {
      if (/^[ \t]*([-*+]|\d+[.)])[ \t]+/m.test(paragraph)) {
        const items = paragraph
          .split('\n')
          .filter((line) => line.trim())
          .map((line) => `<li style="margin:4px 0">${inlineHtml(line.replace(/^[ \t]*([-*+]|\d+[.)])[ \t]+/, ''))}</li>`)
          .join('');
        return `<ul style="margin:10px 0;padding-left:20px">${items}</ul>`;
      }
      return `<p style="margin:12px 0">${inlineHtml(paragraph)}</p>`;
    })
    .join('\n');
}

function inlineHtml(text: string): string {
  return escapeHtml(text)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/(?<!\*)\*([^*\n]+)\*(?!\*)/g, '<em>$1</em>')
    .replace(/\n/g, '<br>');
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Discord embeds cap at 25 fields and 1024 characters per field value. */
export function formatForDiscord(markdown: string, packet: StatPacket): {
  embeds: { title: string; description: string; color: number; fields: { name: string; value: string }[]; footer: { text: string } }[];
} {
  const sections = parseSections(markdown);
  const fields = sections
    .filter((section) => section.heading && section.body)
    .slice(0, 25)
    .map((section) => ({
      name: truncate(section.heading, 256),
      value: truncate(section.body, 1024),
    }));

  const intro = sections.find((section) => !section.heading)?.body ?? '';

  return {
    embeds: [
      {
        title: `${packet.leagueName} — Week ${packet.week}`,
        description: truncate(intro, 4096),
        color: 0x1c1c1e,
        fields,
        footer: { text: FOOTER_TEXT },
      },
    ],
  };
}

/** Slack Block Kit: mrkdwn is not markdown, so bold and bullets are converted. */
export function formatForSlack(markdown: string, packet: StatPacket): {
  blocks: Record<string, unknown>[];
} {
  const sections = parseSections(markdown);
  const blocks: Record<string, unknown>[] = [
    {
      type: 'header',
      text: { type: 'plain_text', text: `${packet.leagueName} — Week ${packet.week}` },
    },
  ];

  for (const section of sections.slice(0, 45)) {
    if (section.heading) {
      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: `*${section.heading}*` },
      });
    }
    if (section.body) {
      blocks.push({
        type: 'section',
        text: { type: 'mrkdwn', text: truncate(toMrkdwn(section.body), 3000) },
      });
    }
  }

  blocks.push({
    type: 'context',
    elements: [{ type: 'mrkdwn', text: `<${FOOTER_URL}|${FOOTER_TEXT}>` }],
  });

  return { blocks };
}

function toMrkdwn(text: string): string {
  return text
    .replace(/\*\*([^*]+)\*\*/g, '*$1*')
    .replace(/^[ \t]*[-*+][ \t]+/gm, '• ')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<$2|$1>');
}

function truncate(text: string, limit: number): string {
  const trimmed = text.trim();
  return trimmed.length <= limit ? trimmed : `${trimmed.slice(0, limit - 1)}…`;
}

export function formatFor(
  target: DeliveryTarget,
  markdown: string,
  packet: StatPacket,
): string | string[] | Record<string, unknown> {
  switch (target) {
    case 'sleeper':
      return formatForSleeper(markdown);
    case 'email':
      return formatForEmail(markdown, packet);
    case 'discord':
      return formatForDiscord(markdown, packet);
    case 'slack':
      return formatForSlack(markdown, packet);
    case 'plain':
    default:
      return `${stripMarkdown(markdown)}\n\n${FOOTER_TEXT}`;
  }
}
